version: "3"

services:
  jupyter-docker-extension:
    image: ${DESKTOP_PLUGIN_IMAGE}
  jupyter:
    image: jupyter/scipy-notebook:lab-4.0.6
    command: jupyter lab --NotebookApp.token='' --NotebookApp.open_browser='False' --NotebookApp.disable_check_xsrf='True' 
    container_name: jupyter_embedded_dd_vm
    restart: unless-stopped
    volumes:
      # - jupyter_data:/home/jovyan
      - D:\Development:/home/jovyan:rw
      - D:\:/host_Data
    environment:
      TZ: America/Los_Angeles
    ports:
      - 58888:8888
volumes:
  jupyter_data:
